PROJECT_NAME = multisense

# Contains your setup() and loop()
PROJECT_SRC_FILE  = multisense.c

# Drivers, etc.
PROJECT_BREEZY_FILES = $(BREEZY_DIR)/drv_i2c_stm32f10x.c \
                       $(BREEZY_DIR)/drivers/mpu6050.c \
                       $(BREEZY_DIR)/drivers/ms4525.c \
                       $(BREEZY_DIR)/drv_ms5611.c \
                       $(BREEZY_DIR)/drivers/hmc5883l.c \
                       $(BREEZY_DIR)/drivers/mb1242.c
	
