PROJECT_NAME = vl53l0x_read

# Contains your setup() and loop()
PROJECT_SRC_FILE  = vl53l0x_read.c

# Drivers, etc.
PROJECT_BREEZY_FILES = $(F1_DIR)/i2c_stm32f10x.c $(F1_DIR)/drivers/vl53l0x.c
