PROJECT_NAME = ms4525

# Contains your setup() and loop()
PROJECT_SRC_FILE  = ms4525.c

# Drivers, etc.
PROJECT_BREEZY_FILES =  $(F1_DIR)/i2c_stm32f10x.c $(BREEZY_DIR)/drivers/mpu6050.c $(BREEZY_DIR)/drivers/ms4525.c
	
