PROJECT_NAME = mb1242read

# Contains your setup() and loop()
PROJECT_SRC_FILE  = mb1242read.c

# Drivers, etc.
PROJECT_BREEZY_FILES = $(BREEZY_DIR)/drv_i2c.c \
		               $(BREEZY_DIR)/drv_mb1242.c
