PROJECT_NAME = hmc5883l_read

# Contains your setup() and loop()
PROJECT_SRC_FILE  = hmc5883l_read.c

# Drivers, etc.
PROJECT_BREEZY_FILES = $(BREEZY_DIR)/drv_i2c.c \
					   $(BREEZY_DIR)/drv_mpu6050.c \
					   $(BREEZY_DIR)/drv_hmc5883l.c
