PROJECT_NAME = accelgyro

# Contains your setup() and loop()
PROJECT_SRC_FILE  = accelgyro.c

# Drivers, etc.
PROJECT_BREEZY_FILES = $(BREEZY_DIR)/i2c_stm32f30x.c $(BREEZY_DIR)/drivers/mpu6050.c
