PROJECT_NAME = multisense

# Contains your setup() and loop()
PROJECT_SRC_FILE  = multisense.c

# Drivers, etc.
PROJECT_BREEZY_FILES = $(F1_DIR)/i2c_stm32f10x.c \
                       $(F1_DIR)/drivers/mpu.c \
                       $(F1_DIR)/drivers/ms4525.c \
                       $(F1_DIR)/drivers/ms5611.c \
                       $(F1_DIR)/drivers/hmc5883l.c \
                       $(F1_DIR)/drivers/mb1242.c
	
