PROJECT_NAME = mpu6050_interrupt

# Contains your setup() and loop()
PROJECT_SRC_FILE  = mpu6050_interrupt.c

# Drivers, etc.
PROJECT_BREEZY_FILES = $(F1_DIR)/i2c_stm32f10x.c $(BREEZY_DIR)/drivers/mpu6050.c
